# Generated by Django 5.2.12 on 2026-03-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('cash', 'Наличные'), ('acquiring', 'Эквайринг')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Завершен'), ('refunded', 'Возвращен'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('bank_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_status', models.CharField(blank=True, help_text='Статус платежа в системе банка', max_length=20, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Последняя синхронизация статуса с банком', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
        ),
    ]
