# Generated by Django 5.2.12 on 2026-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма платежа в системе банка', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_paid_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время оплаты в системе банка', null=True),
        ),
    ]
