# Generated by Django 5.2.12 on 2026-03-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_bank_amount_payment_bank_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма платежа в системе банка', max_digits=10, null=True, verbose_name='Сумма платежа в банке'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_paid_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время оплаты в системе банка', null=True, verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_status',
            field=models.CharField(blank=True, help_text='Статус платежа в системе банка', max_length=20, null=True, verbose_name='Статус платежа в банке'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Последняя синхронизация статуса с банком', null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('completed', 'Завершен'), ('refunded', 'Возвращен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('acquiring', 'Эквайринг')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
